[main]
docker_net_name = "dodeka"

[db]
project = "d-dodeka"
service_name = "db"
# must match <project>-<service_name>-1
container_name = "d-dodeka-db-1"
barman_server_name = "d-dodeka-db-1"
barman_backup_dir = "/dodeka_barman"
postgres_conf_dir = "/dodeka_conf"
init_dir = "/dodeka_init"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/postgres"
host_host = "127.0.0.1"
host_port = "3141"
container_port = "3141"
resources_source = "/postgres_host/db"
resources_target = "/dodeka-db"
volume_name = "db-volume"
db_name = "dodeka"
db_user = "dodeka"
# using default
db_name_admin = "postgres"
image_desc = "Image for D.S.A.V. Dodeka PostgreSQL instance."

[kv]
redisjson_version = "v2.2.0"
project = "ts-dodeka"
service_name = "kv"
# must match <project>-<service_name>-1
container_name = "ts-dodeka-kv-1"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/redis"
host_host = "127.0.0.1"
host_port = "6379"
container_port = "6379"

[server]
project = "s-dodeka"
service_name = "server"
# must match <project>-<service_name>-1
container_name = "s-dodeka-server-1"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/server"
deps_image_name = "ghcr.io/dsav-dodeka/server-deps"
host_host = "127.0.0.1"
host_port = "4241"
container_port = "4241"

[confspawn_env.production]
name = "production"
version = "latest"

[confspawn_env.staging]
name = "staging"
version = "staging"
resources_source = "/postgres_host/db_staging"

[confspawn_env.test]
name = "test"
version = "test"

[confspawn_env.local]
name = "local"
version = "local"
db_password = "postpost"
barman_password = "barbar"
redis_password = "redisredis"