[main]
docker_net_name = "dodeka"

[db]
project = "d-dodeka"
service_name = "db"
# must match <project>-<service_name>-1
container_name = "d-dodeka-db-1"
barman_server_name = "d-dodeka-db-1"
barman_backup_dir = "/dodeka_barman"
postgres_conf_dir = "/dodeka_conf"
init_dir = "/dodeka_init"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/postgres"
host_host = "127.0.0.1"
host_port = "3141"
container_port = "3141"
resources_source = "/postgres_host/db"
resources_target = "/dodeka-db"
volume_name = "d-dodeka-db-volume"
db_name = "dodeka"
db_user = "dodeka"
# using default
db_name_admin = "postgres"
image_desc = "Image for D.S.A.V. Dodeka PostgreSQL instance."

[kv]
redisjson_version = "v2.2.0"
project = "ts-dodeka"
service_name = "kv"
# must match <project>-<service_name>-1
container_name = "ts-dodeka-kv-1"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/redis"
host_host = "127.0.0.1"
host_port = "6379"
container_port = "6379"

[server]
project = "s-dodeka"
service_name = "server"
# must match <project>-<service_name>-1
container_name = "s-dodeka-server-1"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/server"
deps_image_name = "ghcr.io/dsav-dodeka/server-deps"
host_host = "127.0.0.1"
host_port = "4241"
container_port = "4241"
issuer = "https://api.dsavdodeka.nl"
frontend_client_id = "dodekaweb_client"
backend_client_id = "dodekabackend_client"
signup_url = "https://www.av40.nl/index.php?page=Inschrijfformulier&sid=1"
onboard_email = "comcom@dsavdodeka.nl"
smtp_server = "mail.dsavdodeka.nl"
smtp_port = 587

[confspawn_env.production]
name = "production"
version = "latest"
allowed_envs = "\"production\""
# Only the credentials url is with trailing slash, the rest should all be without
api_root = "https://api.dsavdodeka.nl"
valid_redirects = "\"https://dsavdodeka.nl/auth/callback\""
credentials_url = "https://api.dsavdodeka.nl/credentials/"
pages_url = "https://dsavdodeka.nl"

[confspawn_env.staging]
name = "staging"
version = "staging"
allowed_envs = "\"staging\""
api_root = "https://apidemo.tipten.nl"
valid_redirects = "\"https://demo.tipten.nl/auth/callback\""
credentials_url = "https://apidemo.tipten.nl/credentials/"
pages_url = "https://demo.tipten.nl"

[confspawn_env.test]
name = "test"
version = "test"

[confspawn_env.localdev]
name = "localdev"
version = "localdev"
db_password = "postpost"
barman_password = "barbar"
redis_password = "redisredis"
allowed_envs = "\"envless\", \"localdev\", \"test\""
api_root = "http://localhost:4243"
valid_redirects = "\"http://localhost:3000/auth/callback\""
credentials_url = "http://localhost:4243/credentials/"

[confspawn_env.less]
name = "less"
version = "less"