[tool.poetry]
name = "dodeka"
version = "0.4.0"
description = ""
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
confspawn = "^0.2.5"
psqlsync = { git = "https://github.com/tiptenbrink/psqlsync.git", branch = "main", extras = ["dirgh"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
