[main]
docker_net_name = "dodeka"
project = "dodeka"

[db]
service_name = "db"
container_name = "dodeka-db"
postgres_conf_dir = "/dodeka_conf"
init_dir = "/dodeka_init"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/postgres"
host_host = "127.0.0.1"
host_port = "3141"
container_port = "3141"
resources_target = "/dodeka-db"
volume_name = "dodeka-db-volume"
db_name = "dodeka"
db_user = "dodeka"
# using default
db_name_admin = "postgres"
image_desc = "Image for D.S.A.V. Dodeka PostgreSQL instance."

[kv]
redisjson_version = "v2.8.4"
service_name = "kv"
container_name = "dodeka-kv"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/redis"
redis_conf_dir = "/usr/local/etc/redis/redis.conf"
host_host = "127.0.0.1"
host_port = "6379"
container_port = "6379"

[server]
project = "dodeka"
service_name = "server"
container_name = "dodeka-server"
# metaconfig
image_name = "ghcr.io/dsav-dodeka/server"
host_host = "127.0.0.1"
host_port = "4241"
container_port = "4241"
issuer = "https://api.dsavdodeka.nl"
frontend_client_id = "dodekaweb_client"
backend_client_id = "dodekabackend_client"
onboard_email = "comcom@dsavdodeka.nl"
smtp_port = 465
realm="dodeka"

[confspawn_env.production]
name = "production"
version = "v2.3.0"
git_ref = "v2.3.0"
allowed_envs = "\"production\""
# Only the credentials url is with trailing slash, the rest should all be without
api_root = "https://api.dsavdodeka.nl"
valid_redirects = "\"https://dsavdodeka.nl/auth/callback\""
credentials_url = "https://api.dsavdodeka.nl/credentials/"
pages_url = "https://dsavdodeka.nl"
smtp_server = "mail.dsavdodeka.nl"
restart = "always"
mail_enabled = true

[confspawn_env.staging]
name = "staging"
version = "v2.3.0"
git_ref = "main"
allowed_envs = "\"staging\""
api_root = "https://apidemo.tipten.nl"
valid_redirects = "\"https://demo.tipten.nl/auth/callback\""
credentials_url = "https://apidemo.tipten.nl/credentials/"
pages_url = "https://demo.tipten.nl"
smtp_server = "mail.dsavdodeka.nl"
restart = "always"
mail_enabled = true

[confspawn_env.test]
name = "test"
version = "test"
restart = "\"no\""
mail_enabled = false

[confspawn_env.localdev]
name = "localdev"
version = "localdev"
git_ref = "main"
db_password = "postpost"
kv_password = "redisredis"
allowed_envs = "\"envless\", \"localdev\", \"test\""
api_root = "http://localhost:4243"
valid_redirects = "\"http://localhost:3000/auth/callback\""
credentials_url = "http://localhost:4243/credentials/"
smtp_server = "mail.dsavdodeka.nl"
restart = "\"no\""
mail_enabled = false

[confspawn_env.less]
name = "less"
version = "less"
mail_enabled = false