"""create db

Revision ID: 6b37dfffd4bc
Revises: 
Create Date: 2025-09-14 11:01:17.669420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b37dfffd4bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), sa.Computed("CAST(id AS TEXT) || '_' || id_name", ), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('password_salt', sa.LargeBinary(), nullable=False),
    sa.Column('password_hash_algorithm_id', sa.Text(), nullable=False),
    sa.Column('disabled', sa.Integer(), nullable=False),
    sa.Column('email_address_counter', sa.Integer(), nullable=False),
    sa.Column('password_hash_counter', sa.Integer(), nullable=False),
    sa.Column('disabled_counter', sa.Integer(), nullable=False),
    sa.Column('sessions_counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sqlite_strict=True,
    sqlite_with_rowid=False
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
