"""create newuser

Revision ID: b96bcee79ed4
Revises: 6b37dfffd4bc
Create Date: 2025-09-14 15:09:33.323068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96bcee79ed4'
down_revision: Union[str, Sequence[str], None] = '6b37dfffd4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newuser',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_newuser')),
    sqlite_strict=True,
    sqlite_with_rowid=False
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('newuser')
    # ### end Alembic commands ###
