"""create content

Revision ID: a0982c86468d
Revises:
Create Date: 2024-04-30 21:56:00.034152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0982c86468d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_id", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=150), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("content_id", "category", name=op.f("pk_content")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content")
    # ### end Alembic commands ###
