name: Auth CI

on:
  push:
    branches: ['**']
    paths:
      - backend/auth/**
      - .github/workflows/auth-ci.yml
  pull_request:
    paths:
      - backend/auth/**
      - .github/workflows/auth-ci.yml

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: auth-linux-amd64
          - os: macos-latest
            binary_name: auth-darwin-arm64
          - os: windows-latest
            binary_name: auth-windows-amd64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: backend/auth/go.mod
          cache-dependency-path: backend/auth/go.sum

      - name: Build
        working-directory: backend/auth
        run: go build -o ${{ matrix.binary_name }} .
