name: CI DB

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: "dodeka.tipten.nl"
        username: "dodekatest"
        key: ${{ secrets.SSH_PRIVATE_KEY_DODEKATEST }}
        port: ${{ secrets.SSH_DODEKATEST_PORT }}
        script: |
          export DEPLOYID="$(date +%s)"
          gh repo clone DSAV-Dodeka/dodekabackend ~/deployments/deploy$DEPLOYID
    
