name: Deploy DB

on:
  push:
    branches: [ ci ]

jobs:
 deploy:
   runs-on: ubuntu-latest

   env:
     DB_ENV_PASS: ${{ secrets.DB_ENV_PASS }}
     GHCR_TOKEN: ${{ github.token }}
     ACTOR: ${{ github.actor }}

   steps:
   - uses: actions/checkout@v2
   # Third party GH Action, pinned to commit for security
   - name: executing remote ssh commands using ssh key
     uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
     with:
       host: "dodeka.tipten.nl"
       username: "dodekatest"
       key: ${{ secrets.SSH_PRIVATE_KEY_DODEKATEST }}
       port: ${{ secrets.SSH_DODEKATEST_PORT }}
       envs: DB_ENV_PASS,GHCR_TOKEN,ACTOR
       script_stop: true
       # This requires poetry, docker, gpg, bash to be installed on remote
       # Also requires GH CLI logged in with an account with repo read access
       script: |
         export DEPLOYID="$(date +%s)"
         gh repo clone DSAV-Dodeka/dodeka ~/deployments/deploy$DEPLOYID
         gh repo clone DSAV-Dodeka/secrets ~/deployments/secrets$DEPLOYID
         cd ~/deployments/secrets$DEPLOYID
         set -a
         . decrypt.sh secretdb.env.gpg $DB_ENV_PASS
         echo $GHCR_TOKEN | docker login ghcr.io -u $ACTOR --password-stdin
         cd ~/deployments/deploy$DEPLOYID/deploydb
         ./deploy.sh move
