name: Deploy DB

on: workflow_dispatch

jobs:
 deploy:
   runs-on: ubuntu-latest

   env:
     SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
     GHCR_TOKEN: ${{ github.token }}
     ACTOR: ${{ github.actor }}

   steps:
   - uses: actions/checkout@v2
   # Third party GH Action, pinned to commit for security
   - name: executing remote ssh commands using ssh key
     uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
     with:
       host: "116.203.107.52"
       username: "dodeka_github"
       key: ${{ secrets.SSH_HETZNER_PRIVATE_KEY }}
       port: 22
       envs: SECRETS_PASSPHRASE,GHCR_TOKEN,ACTOR
       script_stop: true
       # This requires poetry, docker, gpg, bash to be installed on remote
       # Also requires GH CLI logged in with an account with repo read access
       script: |
         echo $GHCR_TOKEN | docker login ghcr.io -u $ACTOR --password-stdin
         export DEPLOYID="$(date +%s)"
         gh repo clone DSAV-Dodeka/dodeka ~/dbdeployments/deploy$DEPLOYID
         gh repo clone DSAV-Dodeka/secrets ~/dbdeployments/secrets$DEPLOYID
         cd ~/dbdeployments/secrets$DEPLOYID
         set -a
         . decrypt.sh secretdb.env.gpg $SECRETS_PASSPHRASE || exit 1
         cd ~/dbdeployments/deploy$DEPLOYID/use/deploydb
         ./deploy.sh move
