name: Server Build

on:
  workflow_call:
    inputs:
        env:
          required: true
          type: string
    secrets:
      GH_DODEKACOMCOM_TOKEN:
        required: true

jobs:
  build_server:
    runs-on: ubuntu-latest
    env:
      # The place the configuration repo will be placed at temporarily
      SERVER_REPO_PATH: 'dodekabackend'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'DSAV-Dodeka/backend'
          ref: 'main'
          token: ${{ secrets.GH_DODEKACOMCOM_TOKEN }}
          # Relative to ${{ github.workspace }}
          path: ${{ env.SERVER_REPO_PATH }}
      - run: pipx install poetry==1.3.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - name: Config
        run: |
          poetry run confspawn -c config.toml -s ./build/container/server -t ./context -e ${{ inputs.env }}
          poetry run confspawn -c config.toml -s ./build/container/authpage -t ./contextauthpage -e ${{ inputs.env }}
      # First the lock file and project declaration are moved
      # Then the source is moved
      # Then the context for building authpage is prepared
      # dotglob is enabled to also allow the '.*' files to be moved
      # Finally configuration files for building authpage is moved (TEMP until confspawn option)
      - name: Move source
        run: |
          mv ${{ github.workspace }}/${{ env.SERVER_REPO_PATH }}/poetry.lock ${{ github.workspace }}/context
          mv ${{ github.workspace }}/${{ env.SERVER_REPO_PATH }}/pyproject.toml ${{ github.workspace }}/context
          mv ${{ github.workspace }}/${{ env.SERVER_REPO_PATH }}/src ${{ github.workspace }}/context/src
          mv ${{ github.workspace }}/${{ env.SERVER_REPO_PATH }}/authpage ${{ github.workspace }}/context/authpage
          shopt -s dotglob
          mv ${{ github.workspace }}/contextauthpage/* ${{ github.workspace }}/context/authpage
      - name: Cache authpage
        id: cached-authpage
        uses: actions/cache@v3
        with:
          key: authpage-${{ hashFiles(format('{0}/context/authpage', github.workspace)) }}
          path: ${{ github.workspace }}/context/src/apiserver/resources/static/credentials
      - uses: actions/setup-node@v3
        if: steps.cached-authpage.outputs.cache-hit != 'true'
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/context/authpage/package-lock.json
      - name: Build credentials
        if: steps.cached-authpage.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build-mode -- --mode ${{ inputs.env }}
        working-directory: ${{ github.workspace }}/context/authpage
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # We use the repo/action token, which has specified access to the package
          username: ${{ github.actor}}
          password: ${{ github.token }}
      # Set up buildx for later build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Set env from config.toml
      - name: Set env.SERVER_TAG
        if: ${{ github.event_name != 'release' || github.event.action != 'published' }}
        run: |
          export SERVER_IMAGE=$(poetry run confenv -c config.toml -v server.image_name)
          export SERVER_VERSION=$(poetry run confenv -c config.toml -v confspawn_env.version -e ${{ inputs.env }})
          echo "SERVER_TAG=$SERVER_IMAGE:$SERVER_VERSION" >> $GITHUB_ENV
      - name: Set env.SERVER_TAG if release
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: |
          export SERVER_IMAGE=$(poetry run confenv -c config.toml -v server.image_name)
          echo "SERVER_TAG=$SERVER_IMAGE:${{ github.event.release.tag_name }},$SERVER_IMAGE:latest" >> $GITHUB_ENV
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/context
          # Dockerfile tag
          file: ${{ github.workspace }}/context/server.Dockerfile
          tags: ${{ env.SERVER_TAG }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          push: ${{ github.event_name != 'pull_request' }}
