name: Server Build

on:
  workflow_call:
    inputs:
        env:
          required: true
          type: string

permissions:
  packages: write
  contents: read

jobs:
  build-server:
    runs-on: ubuntu-latest
    # In case of production only run when it is a non-prerelease release
    if: ${{ inputs.env != 'production' || (github.event_name == 'release' && !github.event.release.prerelease) }}
    defaults:
      run:
        working-directory: deploy
    steps:
      - uses: actions/checkout@v4
      - name: uv
        id: setup-uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"
          enable-cache: true
          cache-dependency-glob: "./deploy/uv.lock"
      - name: uv sync
        run: uv sync --frozen
      - name: Config
        run: |
          uv run confspawn -c config.toml -s ./build/container/server -t ./context/backend -e ${{ inputs.env }}
          uv run confspawn -c config.toml -s ./build/container/authpage -t ./context/envauthpage -e ${{ inputs.env }}

      # First the lock file and project declaration are moved
      # Then the source is moved
      # Then the context for building authpage is prepared
      # dotglob is enabled to also allow the '.*' files to be moved
      # Finally configuration files for building authpage is moved (TEMP until confspawn option)
      - name: Move source
        working-directory: ${{ github.workspace }}
        run: |
          mv backend/uv.lock deploy/context/backend
          mv backend/pyproject.toml deploy/context/backend
          mv backend/src deploy/context/backend/src
          mv authpage deploy/context/authpage
          shopt -s dotglob
          mv deploy/context/envauthpage/* deploy/context/authpage
      - name: Cache authpage
        id: cached-authpage
        uses: actions/cache@v4
        with:
          key: authpage-${{ hashFiles('deploy/context/authpage') }}
          path: deploy/context/backend/src/apiserver/resources/static/credentials
      - uses: actions/setup-node@v3
        if: ${{ (github.event_name == 'release' && github.event.action == 'published') || steps.cached-authpage.outputs.cache-hit != 'true' }}
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: deploy/context/authpage/package-lock.json
      - name: Build credentials
        if: ${{ (github.event_name == 'release' && github.event.action == 'published') || steps.cached-authpage.outputs.cache-hit != 'true' }}
        working-directory: ${{ github.workspace }}/deploy/context/authpage
        run: |
          npm install
          npm run build-mode -- --mode ${{ inputs.env }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # We use the repo/action token, which has specified access to the package
          username: ${{ github.actor}}
          password: ${{ github.token }}
      # Set up buildx for later build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # *************************************************
      # ************** SET CONTAINER TAGS ***************
      # *************************************************
      ##### Set the base env vars we will need
      # We uniquely identify a commit with its short SHA
      - name: Commit SHA_SHORT
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # We need to use the image name in each tag, so we set that to an env as well
      - name: Image name
        run: echo "IMAGE_NM=$(uv run confenv -c config.toml -v server.image_name -e ${{ inputs.env }})" >> $GITHUB_ENV
      
      ##### not-production will get :<env> and :<env>-<commit sha>, production only gets :<commit sha>
      ##### because for production the 'latest' should only be on a release
      - name: Set base env.IMAGE_TAG not production
        if: ${{ inputs.env != 'production' }}
        run: echo "IMAGE_TAG=$IMAGE_NM:${{ inputs.env }},$IMAGE_NM:${{ inputs.env }}-$SHA_SHORT" >> $GITHUB_ENV
      - name: Set base env.IMAGE_TAG for production
        if: ${{ inputs.env == 'production' }}
        run: echo "IMAGE_TAG=$IMAGE_NM:$SHA_SHORT" >> $GITHUB_ENV
      ##### we only run on a "release" (with type "published") or a "push" event. those have the following values
      #####       PUSH                                  RELEASE
      ##### github.event_name = 'push'    github.event_name = 'release'
      #####        N/A                    github.event.action = 'published'
      #####        N/A                    github.event.release.prerelease = 'true' / 'false'
      # for any release, if not production, we want to add the release name after the env
      - name: Set env.IMAGE_TAG if release and not production
        if: ${{ github.event_name == 'release' && inputs.env != 'production'  }}
        run: echo "IMAGE_TAG=$IMAGE_TAG,$IMAGE_NM:${{ inputs.env }}-${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      # if production, also set latest and the version number without the env
      - name: Add production tag if full release and production
        if: ${{ github.event_name == 'release' && !github.event.release.prerelease && inputs.env == 'production'  }}
        run: echo "IMAGE_TAG=$IMAGE_TAG,$IMAGE_NM:${{ github.event.release.tag_name }},$IMAGE_NM:latest" >> $GITHUB_ENV
      # ************** END SET CONTAINER TAGS ***************
      
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: deploy/context/backend
          # Dockerfile tag
          file: deploy/context/backend/server.Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          push: ${{ github.event_name != 'pull_request' }}
